=== jokimi/SEM4_POIT/ТПвИ/lab3-4+/files/data.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="PrintedProducts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Book" type="PrintedProduct" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element name="Magazine" type="PrintedProduct" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element name="Postcard" type="PrintedProduct" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="PrintedProduct">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="price" type="xs:integer"/>
            <xs:element name="year" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== jokimi/SEM4_POIT/ТПвИ/lab3-4+/files/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<PrintedProducts xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="data.xsd">
    <Book>
        <title>Harry_Potter</title>
        <price>550</price>
        <year>2014</year>
    </Book>
    <Book>
        <title>Paint</title>
        <price>1200</price>
        <year>2003</year>
    </Book>
    <Magazine>
        <title>Lord_of_the_ring</title>
        <price>1000</price>
        <year>2003</year>
    </Magazine>
    <Postcard>
        <title>Times</title>
        <price>70</price>
        <year>2023</year>
    </Postcard>
</PrintedProducts>
